trigger:
- master

pool:
  name: 'aks'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Private ACR'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'Private AKS Connection'
    azureResourceGroup: 'test'
    kubernetesCluster: 'aks'
    command: 'apply'
    arguments: '-f deploy.yaml'